---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2024/3/26 11:50
---

VMTest = { }

function VMTest.RunLua()
    local Sum = 0
    for i=1,100 do
        Sum = Sum + i
    end
    return Sum
end